[package]
name = "rolldhcp"
version = "0.1.1"
edition = "2021"
author = ["edwardzcn-decade <edwardzcn98@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]